@echo off

@echo "Python Test Starting"
@echo "    [@test@]"

@set ANACONDA_DIR=@ANACONDA_DIR@
@echo "ANACONDA_DIR: %ANACONDA_DIR%"

@set PATH=%PATH%;%ANACONDA_DIR%;%ANACONDA_DIR%\Scripts


@set ANACONDA_ENVIRONMENT_NAME=@ANACONDA_ENVIRONMENT_NAME@
@echo "Activating anaconda %ANACONDA_ENVIRONMENT_NAME% Environment... "
CALL %ANACONDA_DIR%\condabin\conda.bat activate %ANACONDA_ENVIRONMENT_NAME%

@set PYTHONPATH=@SIMPL_ANACONDA_OUTPUT_DIR@\@PYTHON_SITE_PACKAGES_NAME@
@echo "PYTHONPATH: %PYTHONPATH%"
cd %PYTHONPATH%

@set PYTHON_TEST_INPUT_DIR=@PYTHON_TEST_INPUT_DIR@
@echo "PYTHON_TEST_INPUT_DIR: @PYTHON_TEST_INPUT_DIR@"

@echo "PYTHON_EXECUTABLE: @PYTHON_EXECUTABLE@"
"@PYTHON_EXECUTABLE@" "%PYTHON_TEST_INPUT_DIR%\@test@.py"
