@echo off

@echo "[@test@] SIMPL Python Test Starting"

@set ANACONDA_DIR=@ANACONDA_DIR@
@set PATH=%PATH%;%ANACONDA_DIR%;%ANACONDA_DIR%\Scripts

@set PYTHONPATH=@SIMPL_ANACONDA_OUTPUT_DIR@\@PYTHON_SITE_PACKAGES_NAME@
cd %PYTHONPATH%
@echo "PYTHONPATH: %PYTHONPATH%"

@set PYTHON_TEST_INPUT_DIR=@PYTHON_TEST_INPUT_DIR@
@echo "PYTHON_TEST_INPUT_DIR: @PYTHON_TEST_INPUT_DIR@"

@echo "PYTHON_EXECUTABLE: @PYTHON_EXECUTABLE@"
"@PYTHON_EXECUTABLE@" "%PYTHON_TEST_INPUT_DIR%\@test@.py"
